### ISSUE TITLE
`workers-ai-provider` not using `gateway` on REST

### ISSUE THREAD

**Issue by demosjarco** [cloudflare/ai#273]
Despite having [the config](https://github.com/cloudflare/ai/blob/c7aa7d24480f1b62cb9ff4bd13956e1b41f44279/packages/workers-ai-provider/src/index.ts#L31C4-L47C2) for it, it never utilizes it.
Also for rest, it probably needs an optional field for `cf-aig-authorization` for REST too.

**Comment by threepointone** [comment]
This should be fixed now

**Comment by demosjarco** [comment]
Testing it out today, as of v3.1.1, it's still not working. Both authenticated and unauthenticated gateway, neither hit the gateway. In ai gateway, there is no log for any of those calls, neither in analytics for requests/token usage/cost.
However the requests go through as usage does appear in the Workers AI dashboard.
